/**
 * Tests fix audit créateurs — couverture createCreator.
 *
 * Exécution :
 *   npx tsx tests/creators/createCreator.test.ts
 *
 * Stratégie : pas d'emulator. On stub les modules `firebase/firestore` et
 * `@/lib/firebase` via `require.cache` AVANT l'import du module sous test
 * (cf. tests/billing/credit-rules.test.ts pour le pattern mini-runner).
 *
 * Couverture (CC1-CC4) :
 *   CC1. createCreator pose un doc avec shape complet (champs requis)
 *   CC2. createCreator marque le user `isCreator=true, role='creator'`
 *   CC3. createCreator double-appel → comportement idempotent côté UI
 *        (les 2 appels font setDoc — overwrite. Idempotence vérifiée par
 *        absence de throw et même creatorId.)
 *   CC4. referralCode est réutilisé si présent sur le user, sinon généré
 */

import Module from 'module';
import path from 'path';

// =====================================================================
// Mini test runner (pattern projet)
// =====================================================================

let _passes = 0;
let _failures = 0;

function pass(label: string): void {
  console.log(`PASS  ${label}`);
  _passes++;
}

function fail(label: string, info?: unknown): void {
  console.log(`FAIL  ${label}`, info ?? '');
  _failures++;
}

function section(title: string): void {
  console.log('');
  console.log(`--- ${title} ---`);
}

function assertEq<T>(actual: T, expected: T, label: string): void {
  if (JSON.stringify(actual) === JSON.stringify(expected)) pass(label);
  else fail(label, { actual, expected });
}

function assertTrue(cond: boolean, label: string): void {
  if (cond) pass(label);
  else fail(label);
}

// =====================================================================
// Mock store (Firestore in-memory)
// =====================================================================

type DocStore = Record<string, Record<string, unknown>>;
const store: { [collection: string]: DocStore } = {};

function resetStore(): void {
  for (const k of Object.keys(store)) delete store[k];
}

function ensureCol(name: string): DocStore {
  if (!store[name]) store[name] = {};
  return store[name];
}

// =====================================================================
// Stub firebase/firestore + @/lib/firebase via require.cache BEFORE import
// =====================================================================

function stubModule(modulePath: string, exports: Record<string, unknown>): void {
  const resolved = require.resolve(modulePath);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const m = new (Module as any)(resolved, module);
  m.filename = resolved;
  m.loaded = true;
  m.exports = exports;
  require.cache[resolved] = m;
}

// Stub firebase/firestore — on remplace toutes les fonctions utilisées par firestore.ts
const fakeServerTimestamp = () => ({ __ts: 'server' });
const fakeIncrement = (n: number) => ({ __inc: n });

interface FakeDocRef {
  __col: string;
  __id: string;
  id: string;
}

let _idCounter = 0;
function newId(): string {
  return `id_${++_idCounter}`;
}

function fakeDoc(...args: unknown[]): FakeDocRef {
  // doc(db, 'col', 'id') OR doc(collRef) → autogenerated id
  if (args.length === 1) {
    const col = (args[0] as { __col: string }).__col;
    const id = newId();
    return { __col: col, __id: id, id };
  }
  const col = args[1] as string;
  const id = args[2] as string;
  return { __col: col, __id: id, id };
}

function fakeCollection(_db: unknown, name: string): { __col: string } {
  return { __col: name };
}

async function fakeSetDoc(ref: FakeDocRef, data: Record<string, unknown>): Promise<void> {
  ensureCol(ref.__col)[ref.__id] = { ...data };
}

async function fakeUpdateDoc(ref: FakeDocRef, data: Record<string, unknown>): Promise<void> {
  const col = ensureCol(ref.__col);
  col[ref.__id] = { ...(col[ref.__id] || {}), ...data };
}

async function fakeGetDoc(ref: FakeDocRef): Promise<{
  exists(): boolean;
  data(): Record<string, unknown> | undefined;
  id: string;
}> {
  const data = ensureCol(ref.__col)[ref.__id];
  return {
    exists: () => Boolean(data),
    data: () => data,
    id: ref.__id,
  };
}

async function fakeGetDocs(_q: unknown): Promise<{ empty: boolean; docs: unknown[] }> {
  return { empty: true, docs: [] };
}

function fakeQuery(...args: unknown[]): unknown {
  return { __query: args };
}

function fakeWhere(...args: unknown[]): unknown {
  return { __where: args };
}

function fakeOrderBy(...args: unknown[]): unknown {
  return { __orderBy: args };
}

function fakeLimit(n: number): unknown {
  return { __limit: n };
}

function fakeWriteBatch(_db: unknown): {
  update: (ref: FakeDocRef, data: Record<string, unknown>) => void;
  commit: () => Promise<void>;
} {
  const ops: Array<{ ref: FakeDocRef; data: Record<string, unknown> }> = [];
  return {
    update(ref, data) {
      ops.push({ ref, data });
    },
    async commit() {
      for (const { ref, data } of ops) {
        await fakeUpdateDoc(ref, data);
      }
    },
  };
}

// Phase mock : on stub `@/lib/firebase` pour fournir un `db` truthy et
// `isFirebaseConfigured`. Le chemin `@/lib/firebase` est aliasé tsconfig
// vers `src/lib/firebase`.
const fakeDb = { __fake: 'firestore' };

const firestoreStub = {
  doc: fakeDoc,
  setDoc: fakeSetDoc,
  getDoc: fakeGetDoc,
  getDocs: fakeGetDocs,
  addDoc: async (col: { __col: string }, data: Record<string, unknown>) => {
    const id = newId();
    ensureCol(col.__col)[id] = { ...data };
    return { id };
  },
  updateDoc: fakeUpdateDoc,
  deleteDoc: async (ref: FakeDocRef) => {
    delete ensureCol(ref.__col)[ref.__id];
  },
  query: fakeQuery,
  collection: fakeCollection,
  where: fakeWhere,
  orderBy: fakeOrderBy,
  limit: fakeLimit,
  onSnapshot: () => () => undefined,
  increment: fakeIncrement,
  serverTimestamp: fakeServerTimestamp,
  Timestamp: { fromDate: (d: Date) => ({ __ts: d.getTime() }), now: () => ({ __ts: Date.now() }) },
  writeBatch: fakeWriteBatch,
  runTransaction: async (_db: unknown, fn: (tx: unknown) => Promise<unknown>) => fn({}),
  startAfter: (...args: unknown[]) => ({ __startAfter: args }),
  GeoPoint: class { constructor(public lat: number, public lng: number) {} },
};

stubModule('firebase/firestore', firestoreStub);

// Stub `@/lib/firebase`. tsx + tsconfig paths : on stub via résolution absolue.
const firebaseLibPath = path.resolve(__dirname, '../../src/lib/firebase.ts');
{
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const m = new (Module as any)(firebaseLibPath, module);
  m.filename = firebaseLibPath;
  m.loaded = true;
  m.exports = {
    db: fakeDb,
    auth: null,
    isFirebaseConfigured: true,
    isStripeConfigured: false,
    isAppReady: false,
    isProductionMode: false,
    getMissingConfig: () => [],
    default: null,
  };
  require.cache[firebaseLibPath] = m;
}

// Stub sendEmail (côté firestore.ts side-effect possible)
const sendEmailPath = path.resolve(__dirname, '../../src/lib/email/sendEmail.ts');
{
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const m = new (Module as any)(sendEmailPath, module);
  m.filename = sendEmailPath;
  m.loaded = true;
  m.exports = { sendEmail: async () => ({ ok: true }) };
  require.cache[sendEmailPath] = m;
}

// =====================================================================
// Import module sous test APRÈS stubs
// =====================================================================

import { createCreator } from '../../src/services/firestore';

// =====================================================================
// Tests
// =====================================================================

async function main(): Promise<void> {
  section('CC1 — createCreator écrit un doc creator avec shape complet');
  resetStore();
  // pré-seed un user sans referralCode → on doit en générer un
  ensureCol('users')['uid-1'] = { uid: 'uid-1', displayName: 'Alice', email: 'a@x.ch' };
  const c1 = await createCreator('uid-1', 'Alice');
  assertEq(c1.creatorId, 'uid-1', 'CC1.a creatorId = uid');
  assertEq(c1.displayName, 'Alice', 'CC1.b displayName posé');
  assertTrue(typeof c1.referralCode === 'string' && c1.referralCode.startsWith('SPORT-'), 'CC1.c referralCode généré (SPORT-XXXX)');
  assertEq(c1.commissionRate, 0.10, 'CC1.d commissionRate default = 0.10');
  assertEq(c1.totalEarnings, 0, 'CC1.e totalEarnings init = 0');
  assertEq(c1.pendingPayout, 0, 'CC1.f pendingPayout init = 0');
  assertEq(c1.isActive, true, 'CC1.g isActive = true');
  assertEq(c1.payoutMethod, 'twint', 'CC1.h payoutMethod default = twint');

  const persisted = store['creators']['uid-1'];
  assertTrue(persisted !== undefined, 'CC1.i doc persisté dans /creators/{uid}');
  assertEq((persisted as { creatorId: string }).creatorId, 'uid-1', 'CC1.j doc persisté creatorId match');

  section('CC2 — createCreator marque user isCreator=true et role=creator');
  const userDoc = store['users']['uid-1'] as { isCreator?: boolean; role?: string };
  assertEq(userDoc.isCreator, true, 'CC2.a user.isCreator = true');
  assertEq(userDoc.role, 'creator', 'CC2.b user.role = creator');

  section('CC3 — double création (idempotence côté UI : pas de throw, même creatorId)');
  resetStore();
  ensureCol('users')['uid-2'] = { uid: 'uid-2', displayName: 'Bob', referralCode: 'SPORT-ABCD' };
  const c2a = await createCreator('uid-2', 'Bob');
  const c2b = await createCreator('uid-2', 'Bob');
  assertEq(c2a.creatorId, c2b.creatorId, 'CC3.a même creatorId sur double appel');
  assertEq(c2a.referralCode, c2b.referralCode, 'CC3.b même referralCode sur double appel');

  section('CC4 — referralCode user pré-existant est RÉUTILISÉ (pas de regénération)');
  resetStore();
  ensureCol('users')['uid-3'] = { uid: 'uid-3', displayName: 'Carol', referralCode: 'SPORT-WXYZ' };
  const c3 = await createCreator('uid-3', 'Carol');
  assertEq(c3.referralCode, 'SPORT-WXYZ', 'CC4 referralCode user réutilisé');
  assertEq(c3.referralLink, 'https://spordateur.com/?ref=SPORT-WXYZ', 'CC4 referralLink construit avec le code user');

  // ==================================================================
  console.log('');
  console.log(`Total : ${_passes} pass / ${_failures} fail`);
  if (_failures > 0) process.exit(1);
}

main().catch((e) => {
  console.error('Test runner crashed', e);
  process.exit(1);
});
